all:
  hosts:
    node1:
      ansible_host: 192.168.0.11
      ip: 192.168.0.11
      access_ip: 192.168.0.11
      ansible_user: YOUR_SSH_USER
      ansible_ssh_private_key_file: YOUR_SSH_PRIVATE_KEY_PATH
    node2:
      ansible_host: 192.168.0.12
      ip: 192.168.0.12
      access_ip: 192.168.0.12
      ansible_user: YOUR_SSH_USER
      ansible_ssh_private_key_file: YOUR_SSH_PRIVATE_KEY_PATH
    node3:
      ansible_host: 192.168.0.13
      ip: 192.168.0.13
      access_ip: 192.168.0.13
      ansible_user: YOUR_SSH_USER
      ansible_ssh_private_key_file: YOUR_SSH_PRIVATE_KEY_PATH
    node4:
      ansible_host: 192.168.0.14
      ip: 192.168.0.14
      access_ip: 192.168.0.14
      ansible_user: YOUR_SSH_USER
      ansible_ssh_private_key_file: YOUR_SSH_PRIVATE_KEY_PATH
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
